apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-kubernetes-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
